# Defines the containers 
services:
  # First project container (can be named anything)
  web:
    # Build parameters for the container
    image: aljovanmp/flight_ticket:latest
    container_name: flight_ticket
    ports:
      # Maps ports to be accessed by the app outside of the container
      - "4000:4000"
    environment:
      MIX_ENV: "prod"
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PWD: ${DATABASE_PWD}
      DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
      DATABASE_DBNAME: ${DATABASE_DBNAME}
      DATABASE_INDICATION: ${DATABASE_INDICATION}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SECRET_KEY: ${SECRET_KEY}

    command: mix phx.server
