name: Deploy Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: aljovanmp/flight_ticket
        registry: docker.io
        dockerfile: dockerfile
        tags: latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Pull image from docker hub
        run: docker pull aljovanmp/flight_ticket:latest
      - name: Delete old container
        run: docker rm -f flight_ticket
      - name: Run docker container
        run: docker compose -f docker-compose.yml up --detach 
        env:
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PWD: ${{ secrets.DATABASE_PWD }}
          DATABASE_HOSTNAME: ${{ secrets.DATABASE_HOSTNAME }}
          DATABASE_DBNAME: ${{ secrets.DATABASE_DBNAME }}
          DATABASE_INDICATION: ${{ secrets.DATABASE_INDICATION }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
